/**
 * generateScenario.ts
 *
 * Calls Claude to generate a new scenario file and writes it to src/data/scenarios/.
 * Automatically adds an import to src/data/scenarios/index.ts.
 *
 * Usage:
 *   ANTHROPIC_API_KEY=sk-... npx ts-node --project tsconfig.scripts.json generateScenario.ts "sneaker drop"
 *   ANTHROPIC_API_KEY=sk-... npx ts-node --project tsconfig.scripts.json generateScenario.ts "flight to miami"
 *
 * Model override: MODEL=claude-sonnet-4-6 ANTHROPIC_API_KEY=sk-... npx ts-node ...
 */

import Anthropic from '@anthropic-ai/sdk';
import * as fs from 'fs';
import * as path from 'path';

const MODEL = process.env.MODEL ?? 'claude-opus-4-7';

const SYSTEM_PROMPT = `You are a script writer for a funny personal finance social media video.
Write a scenario where a Budget Bot intervenes when someone is about to make a questionable purchase.

Rules:
- Be funny and specific. Use realistic dollar amounts.
- Include one embarrassing detail from the user's purchase/social history.
- The bot is gently roasting, not mean.
- The user makes the responsible choice, but reluctantly/defeated.
- The chat list should feel like chaotic real life (worried mom, pretentious friend, landlord, tempting friend, work).
- Keep each bot message line under 60 characters. Use empty strings "" for paragraph spacing.
- Return ONLY valid JSON. No markdown, no explanation.`;

const SCENARIO_INTERFACE = `
The JSON must match this shape exactly:

{
  "id": string,           // PascalCase, no spaces, e.g. "SneakerDrop"
  "chatList": [           // 6-8 contacts
    {
      "name": string,     // display name, can have emoji
      "avatar": string,   // single uppercase letter
      "preview": string,  // last message preview
      "time": string,     // e.g. "9:41" or "Yesterday"
      "unread": number,   // optional, 1-5
      "pinned": boolean   // optional
    }
  ],
  "scenes": [
    {
      "type": "chat-list",
      "tapContact": string,   // name of the contact to tap (should be in chatList)
      "duration": 105
    },
    {
      "type": "conversation",
      "contactName": "💰 Budget Bot",
      "messages": [
        {
          "role": "user" | "bot",
          "lines": string[],    // each string is one line; use "" for blank spacing
          "delayFrames": number // 20-60, gap before this message appears
        }
      ],
      "typingOffset": 45,
      "typingDuration": 18
    },
    {
      "type": "quick-reply",
      "contactName": string,   // the tempting friend who made the offer
      "previewMessage": string, // their original message shown at top
      "userMessage": string,    // user's responsible-but-defeated reply
      "contactResponse": string, // their funny/sad one-line response
      "duration": 440,
      "replyOffset": 50,
      "responseOffset": 110,
      "times": { "preview": "9:15 AM", "reply": "9:41 AM", "response": "9:41 AM" }
    }
  ]
}

The scenes array must have exactly 3 items in this order: chat-list, conversation, quick-reply.
The conversation must have exactly 4 messages: user opener, bot roast, user defeat, bot sign-off.`;

function toKebabCase(id: string): string {
  return id.replace(/([A-Z])/g, (_, c, i) => (i > 0 ? '-' : '') + c.toLowerCase());
}

async function generateScenario(topic: string): Promise<void> {
  const client = new Anthropic();

  console.log(`Generating scenario for: "${topic}" using ${MODEL}...`);

  const message = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: `Generate a scenario JSON for this spending topic: "${topic}"\n\n${SCENARIO_INTERFACE}\n\nReturn only the raw JSON object.`,
      },
    ],
  });

  const rawContent = message.content[0];
  if (rawContent.type !== 'text') throw new Error('Unexpected response type from Claude');

  let jsonText = rawContent.text.trim().replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '');

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(jsonText);
  } catch (e) {
    console.error('Failed to parse JSON:\n', jsonText);
    throw e;
  }

  const id = parsed.id as string;
  const slug = toKebabCase(id);
  const scenariosDir = path.join(__dirname, 'src', 'data', 'scenarios');
  const outputPath = path.join(scenariosDir, `${slug}.ts`);

  const fileContent = `// Auto-generated by generateScenario.ts — topic: ${JSON.stringify(topic)}
import { Scenario } from '../types';
import { makeEmojiAvatar } from '../../utils/makeEmojiAvatar';

export const ${slug.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}: Scenario = ${JSON.stringify(parsed, null, 2)};
`;

  fs.writeFileSync(outputPath, fileContent, 'utf-8');
  console.log(`\nScenario written to: ${outputPath}`);

  // Add import to index.ts
  const indexPath = path.join(scenariosDir, 'index.ts');
  const indexContent = fs.readFileSync(indexPath, 'utf-8');
  const varName = slug.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

  if (!indexContent.includes(slug)) {
    const importLine = `import { ${varName} } from './${slug}';`;
    const updatedScenarios = indexContent
      .replace(/^(import.*\n)+/m, (match) => match + importLine + '\n')
      .replace(/export const scenarios: Scenario\[\] = \[([^\]]*)\];/, (_, inner) => {
        const trimmed = inner.trim();
        const newInner = trimmed ? `${trimmed}, ${varName}` : varName;
        return `export const scenarios: Scenario[] = [${newInner}];`;
      });
    fs.writeFileSync(indexPath, updatedScenarios, 'utf-8');
    console.log(`Added "${varName}" to scenarios/index.ts`);
  }

  console.log(`\nRender with:\n  npx remotion render src/index.ts ${id} --output out/${slug}.mp4`);
}

const topic = process.argv[2];
if (!topic) {
  console.error('Usage: npx ts-node --project tsconfig.scripts.json generateScenario.ts "<topic>"');
  process.exit(1);
}

generateScenario(topic).catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
