/**
 * generateScenario.ts
 *
 * Generates a new scenario.ts file for a given spending topic.
 *
 * Usage:
 *   ANTHROPIC_API_KEY=sk-... npx ts-node --project tsconfig.scripts.json generateScenario.ts "sneaker drop"
 *   ANTHROPIC_API_KEY=sk-... npx ts-node --project tsconfig.scripts.json generateScenario.ts "flight to miami"
 *
 * The model is configurable via MODEL env var (default: claude-opus-4-7).
 */

import Anthropic from '@anthropic-ai/sdk';
import * as fs from 'fs';
import * as path from 'path';

const MODEL = process.env.MODEL ?? 'claude-opus-4-7';

const SYSTEM_PROMPT = `You are a script writer for a funny personal finance social media video.
Your job is to write a scenario where a budget bot intervenes when someone is about to make a questionable purchase.

Rules:
- Be funny and specific. Use realistic dollar amounts.
- Include one embarrassing note from the user's purchase/social history (e.g., they ordered a $60 steak and ate it alone, or they spent $200 on a bar tab for themselves).
- The bot response should be gently roasting, not mean.
- Always end with the user making the responsible choice, but in a defeated, reluctant way.
- The chat list should feel like a chaotic real life (worried mom, pretentious friend, landlord, tempting friend, annoying work message).
- Keep line lengths short — each line of the bot message should be under 60 characters.
- The "triggerContact" should be the tempting friend who offers the bad financial decision.
- Return ONLY valid JSON matching the TypeScript Scenario interface. No markdown, no explanation.`;

const SCENARIO_INTERFACE = `
interface ChatListItem {
  name: string;       // contact display name (can have emoji)
  avatar: string;     // single uppercase letter for avatar circle
  preview: string;    // last message preview text
  time: string;       // time string like "9:41"
  unread?: number;    // optional unread count (1-5)
}

interface Message {
  role: "user" | "bot";
  lines: string[];      // each string is one line; use "" for blank spacing lines
  delayFrames: number;  // frames to wait after previous message (20-60)
}

interface Scenario {
  triggerContact: string;  // name of contact user "taps" in chat list
  chatList: ChatListItem[]; // exactly 5 items
  botConversation: Message[]; // user message, bot response, user reply, bot reply — 4 messages
  resolution: {
    replyTo: string;      // same as triggerContact
    userMessage: string;  // user's responsible-but-defeated reply to triggerContact
    theirResponse: string; // triggerContact's one-line response (funny/sad)
  };
}`;

async function generateScenario(topic: string): Promise<void> {
  const client = new Anthropic();

  console.log(`Generating scenario for topic: "${topic}" using ${MODEL}...`);

  const message = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: `Generate a Scenario JSON object for this spending topic: "${topic}".

The scenario should follow this TypeScript interface:
${SCENARIO_INTERFACE}

Return only the raw JSON object. No markdown code fences, no explanation.`,
      },
    ],
  });

  const rawContent = message.content[0];
  if (rawContent.type !== 'text') {
    throw new Error('Unexpected response type from Claude');
  }

  let jsonText = rawContent.text.trim();
  // Strip markdown code fences if the model included them anyway
  jsonText = jsonText.replace(/^```(?:json|typescript)?\n?/, '').replace(/\n?```$/, '');

  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonText);
  } catch (e) {
    console.error('Failed to parse JSON response:\n', jsonText);
    throw e;
  }

  const outputPath = path.join(__dirname, 'src', 'data', 'scenario.ts');

  const fileContent = `// Auto-generated by generateScenario.ts — topic: ${JSON.stringify(topic)}
import type { Scenario } from './scenario';

export type { ChatListItem, Message, Scenario } from './scenario';

export const scenario: Scenario = ${JSON.stringify(parsed, null, 2)};
`;

  // Write as a standalone scenario file with the generated content inlined
  const standaloneContent = `// Auto-generated by generateScenario.ts — topic: ${JSON.stringify(topic)}

export interface ChatListItem {
  name: string;
  avatar: string;
  preview: string;
  time: string;
  unread?: number;
}

export interface Message {
  role: 'user' | 'bot';
  lines: string[];
  delayFrames: number;
}

export interface Scenario {
  triggerContact: string;
  chatList: ChatListItem[];
  botConversation: Message[];
  resolution: {
    replyTo: string;
    userMessage: string;
    theirResponse: string;
  };
}

export const scenario: Scenario = ${JSON.stringify(parsed, null, 2)};
`;

  fs.writeFileSync(outputPath, standaloneContent, 'utf-8');
  console.log(`\nScenario written to: ${outputPath}`);
  console.log('\nGenerated scenario preview:');
  console.log(JSON.stringify(parsed, null, 2).slice(0, 600) + '...');
}

const topic = process.argv[2];
if (!topic) {
  console.error('Usage: npx ts-node --project tsconfig.scripts.json generateScenario.ts "<topic>"');
  console.error('Example: npx ts-node --project tsconfig.scripts.json generateScenario.ts "sneaker drop"');
  process.exit(1);
}

generateScenario(topic).catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
